app/models/github_repo.rb
spec/models/github_repo_spec.rb

If the repo url specified in site settings has a trailing slash octokit
will raise an 'invalid_repository' error.
This fix strips the trailing slash from any urls specified in
`github_badges_repos` and adds a model test for this as well as a test
for stripping `.git` from the url.

FIX: octokit error with trailing slash in repo name

---

app/lib/github_badges.rb

An easy fix to remove the warning in Rails 6.0.0

FIX: Remove update_attributes! which is deprecated in Rails 6.0.0

---

app/lib/github_badges.rb
spec/lib/github_badges_spec.rb

Previously, the plugin would ignore your commits if you had enabled a setting in GitHub that hides your email addresses and uses its own address instead (e.g. 123+name@users.noreply.github.com)

Match users to commits made from noreply emails

---

app/jobs/regular/create_github_linkback.rb
app/jobs/regular/replace_github_non_permalinks.rb

Zeitwerk is failing when we are searching for Jobs::Onceoff and Jobs::Base without going back to the top-level namespace (this is correlated to the fact that we got Onceoff base class and module with the same name). 
I noticed that in plugins we are using sometimes :: and sometimes not and that gives me comfort that this change will not break anything.
Travis error: https://travis-ci.org/discourse/discourse/jobs/585072364

[WIP] FIX: Use top-level namespace for base classes

---

app/lib/github_badges.rb
spec/lib/github_badges_spec.rb

TIL: GitHub had a different noreply email format before Jul 18, 2017, one without the `id+` prefix (see: https://help.github.com/en/articles/setting-your-commit-email-address#about-commit-email-addresses)

FIX: Handle both no-reply email formats

---

app/lib/github_linkback.rb
spec/lib/github_linkback_spec.rb

If a post contained any variants of PR URL like:
https://github.com/CvX/discourse/pull/8203/commits
https://github.com/CvX/discourse/pull/8203/files
https://github.com/CvX/discourse/pull/8203/checks
…(and with new new github onebox that's the case) the plugin would create an extra linkback every time you'd run the job (i.e. the job was unintentionally non-idempotent)

DEV: Don't post multiple linkbacks for the same PR

---

app/lib/github_badges_repo_setting_validator.rb
app/models/github_repo.rb
config/locales/server.en.yml
config/settings.yml
plugin.rb
spec/lib/github_badges_repo_setting_validator_spec.rb
spec/models/github_repo_spec.rb

This fix is needed because the logs have had the following error on a few instances:
```
Job exception: "$REPO_NAME" is invalid as a repository identifier. Use the repo/user (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys.
```
This was happening because we were not validating the site setting for `github_badges_repos`, and allowing the user to put in any value here, so some people were just putting in a repo name instead of a URL.
We now allow repos in the formats:
* https://github.com/discourse/discourse.git
* https://github.com/discourse/discourse
* discourse/discourse
And we also have a proper setting validator class and tests.

Allow different badge repo format and validate setting

---

app/lib/commits_populator.rb
app/lib/github_linkback_access_token_setting_validator.rb
config/locales/server.en.yml
config/settings.yml
plugin.rb
spec/lib/commits_populator_spec.rb
spec/lib/github_linkback_access_token_setting_validator_spec.rb

A fix/mitigation for this error from the logs:
```
Octokit::Unauthorized: GET https://api.github.com/repos/PSAppDeployToolkit/PSAppDeployToolkit/branches?per_page=100: 401 - Bad credentials // See: https://developer.github.com/v3
```
When we are iterating through all the badge repos to populate commits, if the `github_linkback_access_token` site setting is not correct we get the `Octokit::Unauthorized` error.
To deal with this we:
* Disable the `github_badges_enabled` site setting when encountering the `Octokit::Unauthorized` error.
* Send a PM to the last 10 seen site admins informing them of the issue and what they can do to correct it.
* Validate when saving the `github_linkback_access_token` site setting. We iterate through all the badge repos defined and check whether the token can …

FIX: Disable GitHub badges if invalid octokit credentials found

---

app/lib/github_linkback.rb
config/locales/server.en.yml
spec/lib/github_linkback_spec.rb

The Discourse project doesn't use GitHub issues but we do.
~This PR is **UNTESTED** so it would be somewhat miraculous if this all works properly. Feedback welcome but not expected until I've had a chance to test, I'll update here when I do.~

FEATURE: Add support for GitHub issues

---

app/lib/commits_populator.rb
config/locales/server.en.yml
spec/lib/commits_populator_spec.rb

When we encounter Octokit::NotFound --
- Disable the github_badges_enabled site setting
- Send a PM to the 10 most recently active admins

FIX: Disable GitHub badges if a repository is "Not Found"

---

app/lib/commits_populator.rb
spec/lib/commits_populator_spec.rb

* The `InvalidRepository` error class is not a subclass of `Octokit::Error` so it was not being caught in our rescue block https://github.com/octokit/octokit.rb/blob/14bb1a1d4fec8d2250dc6f6b9cb2d446a0332d58/lib/octokit/error.rb#L316

FIX: InvalidRepository not being rescued and disabling badges job

---

app/lib/github_linkback.rb
spec/lib/github_linkback_spec.rb

This mirrors the discourse-code-review change: https://github.com/discourse/discourse-code-review/pull/21

FEATURE: Linkback only regular posts

---

app/lib/commits_populator.rb
config/locales/server.en.yml
spec/lib/commits_populator_spec.rb

Calls to `disable_github_badges_and_inform_admin` are returning a missing translation error because the `base_url` placeholder is not set. The specs are passing because both the `sent_pm` and the translation from the spec file were returning `translation missing: en.github_commits_populator.errors.repository_not_found_pm`.
This PR adds the `base_path` to the calls that are made when a repo isn't found, or when the repo identifier is invalid. It also makes the links in the PM clickable. Previously the link in the `invalid_octokit_credentials_pm` PM was clickable, but the links returned with the `repository_identifier_invalid_pm` and `repository_not_found_pm` PMs were escaped.

Fix translation not found error for Github badges error messages

---

app/lib/github_badges.rb
spec/lib/github_badges_spec.rb

https://meta.discourse.org/t/nonexistent-users-show-up-on-badge-pages/165533?u=techapj

FIX: do not grant badges to staged users

---

app/lib/github_badges.rb
spec/lib/github_badges_spec.rb

In preparation for core change in https://github.com/discourse/discourse/pull/11170
This change is backwards compatible, so it will continue accessing github_user_infos on older versions of Discourse

DEV: Update GithubUserInfo access to UserAssociatedAccount

---

.rubocop.yml
app/lib/commits_populator.rb
db/migrate/20201210032852_discourse_github_rebuild_git_history.rb

This plugin ships with 2 types of badges: Contributor and Committer.
Currently, these badges are granted by replicating the git history of the
configured repositories in the database using Github's REST API, and
then looking up users by the emails on the commits and hand out badges.
A commit is considered a 'contribution' if it comes from a pull request
that was not created and merged by the same user. The commits endpoint
of Github's REST API doesn't include whether a commit comes from a PR or
not. So, our only way to detect contributions is to compare the
`committer` and `author` fields of the commit object that we get from
the API. This method worked fairly well up until December 2019 when
Github changed something that made the `committer` always be set to
`GitHub` and not the user who …

FIX: Improve contributors detection

---

app/lib/commits_populator.rb
spec/lib/commits_populator_spec.rb

GitHub's GraphQL does not return an error if authentication fails, but
it does not return data either, which is later causing issues.

FIX: No data or error is returned when auth fails

---

app/lib/github_badges.rb
spec/lib/github_badges_spec.rb

The GitHub badge granter GithubBadges::Granter updated user titles
automatically ignoring the allow_title attribute of the badge. This
caused some users to have titles that are not normally allowed.
The user title automatically disappears when Jobs::BadgeGrant runs and
calls BadgeGranter.revoke_ungranted_titles!, so no further action is
required.

FIX: Check if badge can be used as a title

---

spec/jobs/replace_github_non_permalinks_spec.rb

We were adding domains to the blacklist instead of stubbing final destination responses.
This plugin also does not make use of `SiteSetting.blocked_onebox_domains`, and they can rely on core's ability to onebox for blocking.

DEV: Stub response instead of blocking the domain

---

plugin.rb

Fixes a Faraday auth deprecation warning

DEV: Update octokit

---

spec/jobs/replace_github_non_permalinks_spec.rb

There was an `Exception` rescue in core that was hiding an error raised during a spec of this plugin. Core now surfaces exceptions in the test environment which causes the spec to fail now.
Related to https://github.com/discourse/discourse/pull/16150.

DEV: Fix plugin tests following a core change

---

app/lib/github_linkback.rb
config/locales/server.en.yml
config/settings.yml
spec/lib/github_linkback_spec.rb

I am moderating a discourse forum for an open-source app ([AntennaPod](https://github.com/AntennaPod/AntennaPod)). We use the linkback feature to connect the forum with GitHub - which is a great feature.
For every release, we prepare a manual list of changes in that version, linking to the respective GitHub PR (example [here](https://forum.antennapod.org/t/antennapod-2-4-release-notes/1300)). Whenever this happens, followers of the project are flooded with dozens of emails. For example, this is how my inbox looks like (notice that the emails were all sent at the same time). In total, I received around 100 emails from the linkback plugin today.
This PR introduces a setting to define the maximum number of linkbacks to create from a single post. When the number of links is larger than the …

Add setting to limit number of linkbacks per post

---

app/lib/github_badges.rb
db/migrate/20230227050148_update_github_badge_icons.rb

Essentially changing defaults to fab-git
Related: https://meta.discourse.org/t/badges-on-meta/256289

UX: Update badge icon

---

spec/jobs/replace_github_non_permalinks_spec.rb

The `#queue_jobs=` method on site settings has been [deprecated](https://github.com/discourse/discourse/commit/1b65469b64e9e569fed67ae11f1dd9ee37702f5c) and replaced by `Jobs.run_later!` and `Jobs.run_immediately!`. This PR replaces usages in this plugin so we can remove the fallback in core.
The fallback used in core for reference:
https://github.com/discourse/discourse/blob/main/app/models/site_setting.rb#L109-L115

DEV: Replace deprecated queue_jobs site setting in tests

---

config/locales/client.en.yml
config/settings.yml

This is so the plugins settings are better categorized in the site settings UI.

DEV: Change settings root from plugins: to discourse_github

---

config/locales/client.en.yml

Fixes the broken text of the "Discourse GitHub" nav link on the site settings page.

DEV: remove extra en root key from client.en.yml

---

.discourse-compatibility
app/lib/github_linkback.rb

c.f. discourse/discourse@de983796e1b66aa2ab039a4fb6e32cec8a65a098
There will soon be additional login_required checks
for Guardian, and the intent of many checks by automated
systems is better fulfilled by using BasicUser, which
simulates a logged in TL0 forum user, rather than an
anon user.

FIX: Use Guardian.basic_user instead of new (anon)

---

.discourse-compatibility
app/lib/github_linkback.rb

This reverts commit c049ff489f677c827883048053f217bb37b8305e.
c.f. https://github.com/discourse/discourse/pull/24742

Revert "FIX: Use Guardian.basic_user instead of new (anon) (#97)"
